# Generated by Django 2.2.2 on 2019-07-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
