# Generated by Django 2.2.2 on 2019-07-16 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20190717_0623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글들'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': '링크', 'verbose_name_plural': '링크들'},
        ),
        migrations.AddField(
            model_name='comment',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='links.Link'),
        ),
    ]
